package hr.fer.zemris.java.custom.scripting.nodes;

import hr.fer.zemris.java.custom.scripting.parser.SmartScriptParser;

/**
 * Represents a node visitor which visits nodes of the model tree
 * generated by the {@link SmartScriptParser} object from the given
 * expression.
 *
 * @author Luka Čupić
 */
public interface INodeVisitor {

    /**
     * Visits the specified {@link TextNode} node.
     *
     * @param node the {@link TextNode} node to visit
     */
    void visitTextNode(TextNode node);

    /**
     * Visits the specified {@link ForLoopNode} node.
     *
     * @param node the {@link ForLoopNode} node to visit
     */
    void visitForLoopNode(ForLoopNode node);

    /**
     * Visits the specified {@link EchoNode} node.
     *
     * @param node the {@link EchoNode} node to visit
     */
    void visitEchoNode(EchoNode node);

    /**
     * Visits the specified {@link DocumentNode} node.
     *
     * @param node the {@link DocumentNode} node to visit
     */
    void visitDocumentNode(DocumentNode node);
}

