package hr.fer.zemris.java.gui.prim;

import javax.swing.*;
import java.awt.*;

/**
 * A simple program which displays two lists where each contains
 * prime numbers. Each prime number can be generated by clicking
 * the "Next" button on the bottom of the program.
 *
 * @author Luka Čupić
 */
public class PrimDemo extends JFrame {

    /**
     * The constructor.
     */
    public PrimDemo() {
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(420, 300);
        setVisible(true);
        setTitle("Prime Demo v1.0");

        initGUI();
    }

    /**
     * A helper method which initializes the GUI.
     */
    private void initGUI() {
        setLayout(new BorderLayout());

        PrimListModel model = new PrimListModel();
        JList<Integer> list1 = new JList<>(model);
        JList<Integer> list2 = new JList<>(model);

        JPanel center = new JPanel();
        center.setLayout(new GridLayout(0, 2));
        center.add(new JScrollPane(list1));
        center.add(new JScrollPane(list2));

        JButton next = new JButton("Next");
        next.addActionListener(l -> model.next());

        add(center, BorderLayout.CENTER);
        add(next, BorderLayout.PAGE_END);
    }

    /**
     * The main method.
     *
     * @param args command line arguments; not used in this program
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(PrimDemo::new);
    }
}
